---
abstract: 'Perl extension to detect on which Linux distribution we are running.'
author:
  - 'Alexandr Ciornii <alexchorny@gmail.com>'
generated_by: 'Module::Build version 0.3617'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Linux-Distribution
provides:
  Linux::Distribution:
    file: lib/Linux/Distribution.pm
    version: 0.20
requires:
  Test::More: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/chorny/Linux-Distribution
version: 0.20
